elementary/granite

- lib/Widgets/AppMenu.vala
This is a pretty silly widget. It exists to set two properties.
> Deprecate Granite.Widgets.AppMenu

- lib/Widgets/Avatar.vala
This doesn't change API at all, just changes variable names and documentation to match how Gtk refers to int sizing for icons
icon_size in Gtk refers to the enum [Gtk.IconSize](https://valadoc.org/gtk+-3.0/Gtk.IconSize.html)
> Avatar: change icon_size to pixel_size

- lib/Widgets/Welcome.vala
This makes WelcomeButton behave more similarly to normal buttons; instead of looking for the release event, we look for the click event. 
Gtk handles this slightly differently by requiring the press and release to be performed inside of the widget, which has a side effect of allowing a sort of cancel when you press, then drag outside the widget, then release.
> Switch WelcomeButton from button_release_event to clicked

- demo/CMakeLists.txt
- demo/GraniteDemo.vala
- demo/Views/SourceListView.vala
- demo/Views/WelcomeView.vala
The number of items has really outgrown the welcome widget. This replaces using the welcome for navigation with a Gtk.StackSidebar and creates a new Welcome view with only two items.
I also added a frame and some margin to SourceList because it looked freakin weird
> Demo: Replace Welcome with a StackSidebar

- lib/Widgets/AboutDialog.vala
* Remove unused Granite.Drawing.BufferSurface
* Remove obvious comments on private vars
* Group all action_area properties and methods
* Connect signals at the end
* Space before parentheses
> Widgets.AboutDialog.vala: code style cleanups

- lib/Widgets/OverlayBar.vala
This actually got merged after 0.4.1 was released so this should be 0.4.2 which will (probably) be the next version including this deprecation
> OverlayBar.vala: bump version number on deprecation

- lib/Widgets/Utils.vala
This may have made sense at the time, but setting a style class is a one-liner in Gtk already and these text style classes have constants defined elsewhere in Granite
> deprecate text style methods which are one-liners in gtk already

- lib/Widgets/DynamicNotebook.vala
`DynamicNotebook.insert_tab` returns an unsigned integer, but uses `GLib.return_if_fail` instead of the correct `GLib.return_val_if_fail`. Presumably this would only result in a warning on a native elementaryOS build, but on macOS with clang, this produces a compile error instead:
```
.../granite/build/lib/Widgets/DynamicNotebook.c:4159:2: error:
non-void function 'granite_widgets_dynamic_notebook_insert_tab' should
return a value [-Wreturn-type]
g_return_if_fail (_tmp3_ < 0);
```
This error blocked granite from being included in Homebrew in the past; see https://github.com/Homebrew/homebrew-core/pull/1139. (The following is not in the commit message.) The people who first noticed this error thought that the official granite repository was on Launchpad and [reported it …
> DynamicNotebook: fixed return_if_fail in non-void method insert_tab leading to a build error on macOS

- lib/Widgets/Avatar.vala
I've been doing some investigation into some of the HiDPI issues with the greeter to try and get a better understand of the code and one of the things that stood out to me was the scale of the Avatar widget. While all the other widgets sort of resize themselves when they detect the scaling of the screen, the Avatar doesn't.
This is reproducible by running the granite-demo and adjusting the display's scale factor with the org.gnome.desktop.interface.scale-factor key. All the GTK widgets resize OK, but the Avatar doesn't. This change now reloads the pixbuf and resizes the widget when the DPI of the monitor changes and hence fixes the issue in the Greeter.
The only downside of this is that it won't have any effect on Avatars that have had their pixbuf directly set by the calling code rather …
> Reload and resize Avatar on DPI change

- lib/Widgets/Toast.vala
Fixes the Widgets.Toast introduction being outside of the class, so they appeared in the `Utils` namespace instead of the `Toast` class.
> Fix Toast introduction

- lib/Widgets/Utils.vala
This PR completes and fills the documentation for undocumented symbols in lib/Widgets/Utils.vala. Some of these have now a more useful description of how to use them and hints about what methods to use when calling them.
I would like to have it reviewed by someone that knows English very well, I'm not a native speaker but I've tried to do my best.
> Document Utils.vala

- lib/Application.vala
Fixes #80.
This branch entirely removes the `Granite.app` static field which prevented destructors from being ran. I would say this change is high priority since it can cause confusion for developers, as seen in #80.
> Remove deprecated and buggy app instance

- demo/GraniteDemo.vala
- lib/Application.vala
- lib/Widgets/AboutDialog.vala
Since the plan is that going forward all apps should have this data in their appdata.xml (and thus AppCenter) instead
> Deprecate About Dialog

- lib/Widgets/Utils.vala
Deprecated since who knows when, but we removed the close pixbuf a while ago
> Remove deprecated get close pixbuf

- lib/Widgets/DynamicNotebook.vala
Changes tab middle click event from `button_press_event` to `button_release_event` to fix #82.
> Middle clicks close tabs on release instead of press

- lib/Application.vala
The options were added to an internal `OptionContext` created within `run` and didn't take any other options into account. We now add the options with the native `add_main_option_entries` method in `GLib.Application` so that all the options that get added into the application are parsed correctly. To apply the options we connect to `handle_local_options` signal which is fired after all options were parsed. More info here: https://valadoc.org/gio-2.0/GLib.Application.handle_local_options.html
> Fix handling debug option blocking other options from showing in help

- lib/Widgets/Utils.vala
Makes the schema lookup recursive since it wasn't found directly: 
https://valadoc.org/gio-2.0/GLib.SettingsSchemaSource.lookup.html
Fixes gala throwing the following errors when opening the multitasking view:
```
** (gala:27187): WARNING **: Utils.vala:268: No schema indicating the button-layout is installed...
```
> Make settings lookup recursive

- lib/Widgets/TimePicker.vala
Corrects the behaviour of hours beginning with 12 with a suffix, allows giving times without a separator such as 6am or 1230 or 7.
Fixes #114
> Better parse text input to TimePicker

- lib/Widgets/DynamicNotebook.vala
* Replace deprecated `margin_left` and `margin_right`
* Remove deprecated Gtk vendor prefixed styles
* `Gtk.Button.from_icon_name` is a thing
* Replace deprecated `Gtk.ImageMenuItem`
* Remove unnecessary box
* Fix margins
> DynamicNotebook: misc cleanup

- lib/Widgets/DatePicker.vala
This updates the popover calendar's selected date when the date is set for the DatePicker.
Fixes #112
> Update popover calendar when setting date

- lib/Widgets/SettingsSidebar.vala
This unbreaks search in Switchboard. Setting the visible child in the stack seems to get overridden by what is selected in the sidebar. This allows us to set the selected child in the sidebar and thus the visible child in the stack
> Add a visible child name property to SettingsSidebar

- lib/Widgets/AlertView.vala
Limits line length to 75 characters because infinite line lengths aren't fun to read
> AlertView.vala: max char width

- lib/Drawing/Color.vala
- Adds a two new construction methods for passing a string, and passing a Gdk.RGBA on constructors
- adds a `to_string ()` method that returns the contents of the class to a CSS compatible string
Question: 
Should we deprecate the `Gdk.Color` constructor?
> Granite.Color: Parse and to_string

- lib/Widgets/DynamicNotebook.vala
Because of this, the restore features were not always working with `Ctrl` + `w` (especially with Code)
> DynamicNotebook: make the keybinding trigger the right signal

- demo/Views/ModeButtonView.vala
- lib/Widgets/ModeButton.vala
This is my attempt at fixing the cosmetic glitch in #67 without breaking backward compatibility. However:
* I'm not sure if `can_deselect` is the best name for this property within the larger Gtk universe.
* I'm also not sure if deselection is a supported feature of the ModeButton right now. The `selected` property is not updated to -1 when it happens and it can't be observed using the `mode_changed` signal, and "fixing" that could break apps which don't expect deselection to happen.
If no app relies on the current deselection behavior, it might be better to *always* prevent deselection instead of making it configurable. That would also fix affected apps without changing their code.
* The code I've added relies very much on the order of execution to distinguish user events from …
> Prevent ModeButton deselection (for #67)

- lib/Widgets/OverlayBar.vala
Fixes #110 
This is a compromise solution with less chance of side-effects by keeping constuctor signature the same.
Will be followed by a further PR to remove overlay as constructor parameter in the interests of maintainability.
> Deprecate overlay property in OverlayBar

- lib/Widgets/AlertView.vala
- lib/Widgets/Avatar.vala
- lib/Widgets/OverlayBar.vala
- lib/Widgets/SeekBar.vala
- lib/Widgets/StorageBar.vala
- lib/Widgets/Welcome.vala
This adds code examples (from granite demo) for several widgets:
* Alertview
* Avatar
* OverlayBar
* SeekBar
* StorageBar
* Add an "example" label to Welcome view to be consistent
> Add code examples

- lib/Widgets/AbstractSimpleSettingsPage.vala
Fixes the vertical alignment of the switch and title for SimpleSettingsPages that don't have a description.
> SimpleSettingsPage: Valign title with no description

- lib/Widgets/DynamicNotebook.vala
Fixes a warning about deprecated Gtk.Widget.override_background_color 
* We already set button padding for notebook tabs to 0 in the stylesheet so remove `fix_button_theming ()`
* Overriding tab background color doesn't seem to have any visual effect either
* Remove margins from the add-button since this was causing an oddly shaped box
* Valign close button to get a square box
* Reduce margin on restore button so that it aligns with window controls
> DynamicNotebook: Style cleanups

- lib/Widgets/SourceList.vala
Since this is a TreeView and it's very difficult to do CSS class based stuff on the text. It would be good to allow markup on items. This would allow me to do something a bit neater with https://github.com/elementary/code/pull/452 and show the branch names inline with the project name without it looking weird.
> Add a markup property to SourceList.Item

- lib/Application.vala
Officially deprecate Granite.Application
I think the only thing we were holding onto here is the --debug flag which we agreed is already covered by `--gtk-debug`
> Deprecate Granite.Application

- lib/DateTime.vala
The date format in US English should include commas such as "Thu, Aug 2, 2018" and "Thu, Aug 2"
> DateTime: Add commas in date format

- lib/Widgets/SourceList.vala
Use Gtk.Paned instead of Granite.Widgets.ThinPaned which was deprecated in 0.5
https://github.com/Valadoc/valadoc-org/issues/181
> Updated Example

- lib/Widgets/TimePicker.vala
* Organize private variables
* Put constructor above the construct block
* Add missing brackets
* Keep popover stuff together
* Don't use a constant for a value that's only used one time
* Don't set `popover_position` every time the icon is clicked
* Point the popover at the entry icon area (duh)
> TimePicker: misc cleanup

- lib/DateTime.vala
This particular PR will fix elementary/calendar#268 and fix elementary/calendar#91.
This will only fix those issues for Calendar in elementary, but it will probably break things in other systems that don't have the wingpanel indicator, or a way to change the format of the wingpanel indicator.
Either way, it seems reasonable to expect Granite to respect the system setting for elementary over anything else.
> Change settings to look at a more relevant value for time format

- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
Reverses the order of arguments and allows the description to be null to accommodate text buttons
> Allow description to be null

- demo/CMakeLists.txt
- demo/GraniteDemo.vala
- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
Fixes #228 
Adds two new utils:
* `accel_to_string`, which takes something like `"<Super>Right"` and returns `"⌘ + →"`
* `markup_accel_tooltip`, which takes a description and an accel string array and returns the markup pictured below for tooltips
>  Add utilities for marking up accel tooltips

- lib/Widgets/Utils.vala
While looking into the Applications menu tooltip I noticed that the keybinding settings would return an array with an empty string, causing tooltips to look like:
Example code applications menu that would return array with empty string when keyboard shortcut was set to Disabled.
```
private const string KEYBINDING_SCHEMA = "org.gnome.desktop.wm.keybindings";
var keybinding_settings = new GLib.Settings (KEYBINDING_SCHEMA);
keybinding_settings.get_strv ("panel-main-menu");
```
This PR checks for empty accel strings and ignores them.
I've also implemented this filter in the applications-menu itself: https://github.com/elementary/applications-menu/pull/161
> Ignore empty accel strings

- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
It looks like currently passing "Enter" to `markup_accel_tooltip` results in a blank label, and passing "Return" lists that as the key (even though everywhere else we refer to the key as "Enter". This fixes the latter case.
> Handle 'Return' key

- lib/Services/System.vala
A lot of our apps are not testing if privacy mode is enabled to prevent things like recent files from showing up. But adding a settings dependency to `org.gnome.desktop.privacy` on every app that wants to check if privacy mode is enabled could be prevented by a helper function in Granite. This PR adds said function, and makes is to that if the setting is not found (Different OS or maybe GNOME changed the schema) it will just return `true` and the apps can act as normal
Terminal: PR to stop Tabs from being saved https://github.com/elementary/terminal/pull/349
Spice-Up: Stop saving the used files while it's enabled: https://github.com/Philip-Scott/Spice-up/pull/260
Videos also has the direct dependency at tihs line on [Window.vala](https://github.com/elementary/videos/blob/59dc6d61b0ad4a7e91 …
> Add function to check if history is enabled within the privacy settings

- lib/Widgets/TimePicker.vala
Just changes to Timepicker.vala from #213 
Also try to reduce redundant comparisons in `parse_time`
> TimePicker: Use more compact boolean comparison syntax

- README.md
This completes #265 and #266 by adding the new meson requirement to the build dependencies in README.md
> Require Meson >=0.48.2 Part 2

- lib/Services/IconFactory.vala
According to GitHub search, this class is never used in any project
> Deprecate unused IconFactory

- lib/Services/System.vala
All these utilities should be deprecated for a couple of reasons:
1. They're provided by GLib.AppInfo in few lines already so there's no real convenience benefit
2. These utilities don't return an Error and apps should really handle their errors in a more graceful way than just terminal output, with at least some kind of feedback in the UI.
Contents of the utilities have been replaced to not internally use deprecate methods so we don't get deprecation warnings when building Granite.
> System: deprecate utilies provided by GLib

- lib/Widgets/Utils.vala
Fixes #274 
Before: `Alt_L` is parsed to `Alt L`
After: `Alt_L` is parsed to `Alt (Left)`
> Utils: Add more keys to accel-to-string

- demo/Views/MessageDialogView.vala
Current copy is a big verbose. Also use Title Case while we're here
> MessageDialogView: Make copy more concise

- lib/Widgets/DynamicNotebook.vala
Fix for #294 and https://github.com/elementary/code/issues/485: Dynamic notebook: Rapidly closing tabs with three-finger/middle
click button re-opens closed tabs
Changing `child_revealed` to `reveal_child` to make tab close-able by middle/three-finger click during
reveal animation. This prevents the creation of new tabs when trying to rapidly close multiple tabs.
**Before**
**After**
> Fix #294: Rapidly closing tabs with three-finger/middle click button re-opens closed tabs

- lib/Widgets/DynamicNotebook.vala
- po/eo.po
- po/it.po
1. Merges weblate/master, [which had conflicts for Italian and Esperanto](https://l10n.elementary.io/projects/desktop/granite/#alerts) (not sure how these happened?!)
2. Adds a translation hint for "Close All Tab(s) on the Right" for RTL environments
> Localization fixes

- lib/Widgets/DynamicNotebook.vala
Reverts elementary/granite#299
It seems like this causes segfaults in Code which were also foresighted by the discussion in https://github.com/elementary/granite/pull/301. Oops.
> Revert "More efficient code for closing to the right"

- lib/meson.build
See issue #241 for context.
Passing libgranite.full_path() to g-ir-compiler during the build
results in a typelib which references the local build path, which
doesn't correspond to the actual build path in the binary that's
shipped to the users in the packaged version of libgranite.
Removing the path component and leaving only the output library
filename here still works as expected.
> Remove path from --shared-library flag

- lib/Widgets/Toast.vala
…instead of `close-symbolic`. This icon is provided by Adwaita and Yaru. It's also self-consistent since we use it in Dynamic Notebooks:
https://github.com/elementary/granite/blob/40e7d08c0fb7921104a1f2d362e8862dabc02c8c/lib/Widgets/DynamicNotebook.vala#L238
We symlink it in the icons anyway: https://github.com/elementary/icons/blob/master/actions/symbolic/close-symbolic.svg
> Use window-close-symbolic in toasts

- lib/Services/Application.vala
- lib/Services/AsyncMutex.vala
- lib/meson.build
The `lock` keyword only locks across different threads, rather than different calls to `async` methods on the same thread.
We were seeing an issue with AppCenter where the badge wouldn't appear and we'd get the following messages in the console:
```
Client.vala:95: An object is already exported for the interface com.canonical.Unity.LauncherEntry at /com/canonical/unity/launcherentry/3980099301
```
This was due to a race condition where `set_badge` and `set_badge_visible` were called in quick succession to each other.
In this case, the first call is still yielding on `GLib.Bus.@get` with `instance = null`, the second call sees that `instance == null` and continues to try and create a new instance and register on the bus again, which fails.
I've created this generalized async locking class …
> Use async mutex for badge synchronisation

- lib/Widgets/AbstractSettingsPage.vala
- lib/Widgets/AbstractSimpleSettingsPage.vala
two-in-one since they're so small and just trailing whitespace
> Abstract Settings Pages: Lint

- lib/Services/Logger.vala
Public variable gets a lint exception comment. I believe `isForeground` was internal so `is_foreground` should be fine.
> Logger: Lint

- lib/Drawing/BufferSurface.vala
A ton of end-of-line whitespace changes, so probably best viewed with whitespace changes off. With variable name changes, we need to make sure they were all internal and don't affect API.
> BufferSurface: Lint

- lib/Widgets/DynamicNotebook.vala
Any idea what this was for?
Seems that Tom added it [here](https://github.com/elementary/granite/commit/e7f12f36438ded8cfb973c84cf29b419ccc8a3ff) 8 years ago. No idea what it's supposed to do. Seems like nothing :p
> DynamicNotebook: Get rid of the big spinner

- lib/Widgets/Settings.vala
Prevents critical errors being logged when a key other than the color scheme key is changed on the interface.
> Null check color scheme

- lib/Widgets/Utils.vala
Fixes #385. Turns out the translation was coming from Gdk, not us.
> accel_to_string: explicitly set backslash string

- lib/Widgets/Toast.vala
Closes #321.
I added signal handlers so that when a mouse pointer enters the toast, the timeout is stopped and when it leaves, a new timeout is started.
While I was at it, I also abstracted the start and stop logic for timeouts into separate functions.
---
One edge case that I discovered and fixed was that if you:
1. close a timeout by clicking the close button or the action button
2. remove your mouse pointer from the toast
3. immediately retrigger the notification
then the old timeout started by the `leave_notify_event` will kick in and hide the toast prematurely. To fix this, I stopped the timeout unconditionally inside `send_notification ()`.
> Stop the timeout when hovering the toast

- lib/Widgets/Utils.vala
Currently these report as "Control L" and "Control R".
I guess we should decide whether it should be "Left Control" or "Left Ctrl"
Some context:
> Utils: accel_to_string add Ctrl_L and Ctrl_R

- data/granite.appdata.xml.in
- demo/Views/DynamicNotebookView.vala
- lib/Widgets/DynamicNotebook.vala
Allow apps to set a tooltip with additional information rather than just repeating information that is already visible in the tab label (although the label could be ellipsized)
> Expose tab label tooltip

- data/granite.appdata.xml.in
- lib/Constants.vala
- lib/meson.build
- po/POTFILES
Fixes #429 
I opted for only these two constants because it seems the material guidelines only recommend the longer transition durations for things like changing pages, open dialogs, etc. Dialog animation duration is not controlled by apps and the default transition duration for stack is already 300ms. I also left off the state/element transition since I can't think of any examples where we would use this currently outside the stylesheet. If it turns out we do want to use these other transition values I figure we can add them in a follow-up branch
> Constants: Add transition durations

- demo/io.elementary.granite.demo.desktop
As discussed in https://github.com/elementary/gala/pull/939#issuecomment-716912596
Because the exec name does not match the desktop file, we need to give Gala a hint on how to match the window to the desktop file.
This will resolve the fact that the Granite Demo no longer has an icon in the window switcher, multitasking view, etc... with the latest Gala dailies.
> Add StartupWMClass for demo

- lib/Widgets/Utils.vala
There's probably a better name for this, but this does the least to make this markup re-usable in other contexts. For example in indicators for middle-click functions and in the Files sidebar for storage devices
Supersedes #446
> Utils: make tooltip secondary text markup public

- lib/Widgets/MessageDialog.vala
Make sure we use the correct `messagedialog` css name instead of just `dialog`
> MessageDialog: use messagedialog css name

- lib/Widgets/Settings.vala
Could be handy for
- https://github.com/elementary/gala/pull/1104
- https://github.com/elementary/switchboard-plug-pantheon-shell/pull/263
> Get prefers accent color from AccountsService

- data/granite.appdata.xml.in
- lib/Widgets/Utils.vala
- meson.build
Turns https://github.com/elementary/calculator/pull/177/ into a one-liner.
> Utils: add force_elementary_style ()

- data/granite.appdata.xml.in
- lib/Widgets/Settings.vala
Reverts elementary/granite#483
This seems only interesting to two very specific applications and isn't a good long-term solution for flatpak'd apps, as we don't really want them to be adding accountsservice to their sandbox.
> Revert "Get prefers accent color from AccountsService"

- data/granite.appdata.xml.in
- lib/Widgets/Utils.vala
@tintou requested we revert this and instead handle it in the Flatpak platform, which makes sense.
> Revert adding force_elementary_style

- data/granite.appdata.xml.in
- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
This fixes the accel_to_string function so that it does not always add " + " to any accel passed to it. This is created to address a comment on [this pull request](https://github.com/elementary/applications-menu/pull/480) and includes an update to the demo to include both an accel without any mod and an accel that is only a mod.
> Fix accel_to_string to not automatically add a '+' character unless needed

- lib/Widgets/ModeButton.vala
Fixes #504 
No idea why this was set to disallow focus. I can't seem to find any regressions allowing the widgets to be focused
> ModeButton: allow keyboard focus

- lib/Widgets/Utils.vala
If you pass `accel_to_string` to a accel that only contains modifiers e.g. "\<Shift\>\<Control\>" or "\<Shift\>\<Alt\>", it only return either of them, as seen in Shortcut Overlay:
> Make sure to work accel_to_string with multiple modifiers

- data/granite.appdata.xml.in
From [the comment](https://l10n.elementary.io/translate/desktop/granite-extra/en/?checksum=9a5cffb934bf6f0e#comments) by supaeasy in weblate.
> appdata: Fix a typo

- lib/Widgets/Settings.vala
Closes #512.
I skipped the bullet hyphen because it wouldn't make sense for JSON manifests.
I am not sure if backticks are the right way to mark up code in Valadoc. Let me know if it is incorrect.
> Add instruction for accessing AccountsService from Flatpak

- lib/Widgets/AbstractSettingsPage.vala
Per a discussion in Slack.
Currently, the main container of a SettingsPage can scroll horizontally. This can lead it to truncate its contents, which looks strange. For example, in the privacy settings page:
This PR disables horizontal scrolling so that the window is restricted to the horizontal size of the settings page children.
From previous experiments in the Gtk debugger, it seems like this should work. I'm not sure how to test it without overwriting my system Granite install (not sure the consequences of that one), since some container higher up in the granite-demo window appears to allow its children to be horizontally truncated. (I tested it on other settings pages, which were all truncated the same way, so I don't think the behavior I'm seeing in the demo is a result of …
> Disable SettingsPage horizontal scrolling

- lib/Widgets/Utils.vala
This appears to be used only once in Gala
> Utils: Remove Granite.CloseButtonPosition

- data/granite.appdata.xml.in
We had two classes named "Settings": `Granite.Service.Settings` which have just removed and `Granite.Settings` for color preferences. This is really a tiny thing but we may want to explicit that the removed Settings class here is the one in the Service namespace and not the latter one.
> AppData: Explicit namespace of the removed Settings

- lib/Services/System.vala
These private static functions aren't used. Removes a terminal warning
> System: remove unused functions

- lib/Widgets/HyperTextView.vala
Make sure focus is switched to the browser when launching. Gtk.show_uri includes its own error dialog
> HyperTextView: Use Gtk.show_uri

- lib/Widgets/SettingsSidebarRow.vala
We added icons with proper names here: https://github.com/elementary/icons/pull/988
also handle StatusType.NONE to fix terminal warning
> SettingsSidebarRow: Use semantic icon names

- demo/GraniteDemo.vala
- demo/Views/SettingsView/SettingsView.vala
Properly resize panes when changing the size of the window: sidebars don't resize
> GraniteDemo: fix pane resizing

- debian/changelog
The release action just bumps the previous package name, but we renamed for this release.
> debian: Rename package in changelog

- data/granite.appdata.xml.in
- demo/Views/CSSView.vala
- lib/Constants.vala
This class is currently used in Gtk.Inspector, Gtk.WidgetFactory, and Gtk.Demo. It sounds like it may change upstream in future releases, such as to `boxed-list` or something else, but in general having a style class that sets some standard padding/sizes/etc on Gtk.ListBox is useful and we support it in the stylesheet
Todo:
> Constants: Add STYLE_CLASS_RICH_LIST

- data/granite.appdata.xml.in
- lib/Constants.vala
Adds the missing style classes discussed in https://github.com/elementary/granite/issues/617 as constants
> Added missing style constants (sidebar + background)

- demo/Views/ToastView.vala
- lib/Widgets/Toast.vala
When the 'Grantie.Toast' title gets too long, for example when used to toast long filenames, the 'Granite.Toast' continues to expand horizontally regardless of the parent window. This aims to fix it.
**Before** 
**After**
> Make Toast Wrap

- lib/Widgets/AbstractSimpleSettingsPage.vala
* Wrap titles instead of ellipsize
* Valign switches so they always sit in the top right corner, even with wrapped titles
* Let description text go under the switch
> SimpleSettingsPage: layout text smarter at small widths

- lib/Constants.vala
This style class is used by Gtk.Image, so we support it too. See also https://github.com/elementary/stylesheet/pull/1222
> Constants: add large-icons

- demo/Views/CSSView.vala
- lib/Widgets/HeaderLabel.vala
As I'm working with more settings panes in particular I'm finding that I want to add description text below certain headers, but because of the built in extra spacing in headers it makes the layout kind of awkard. I'd like to be able to have spacing and sizing kind of specific for this case so we always have nice typography in this kinds of headers:
With a little CSS: https://github.com/elementary/stylesheet/pull/1228
> HeaderLabel: add optional body text

- lib/Widgets/SettingsSidebarRow.vala
This fixes the weird empty space below a SettingsSidebarRow's title when there's no status string set.
That way, the options in e.g. the Mouse switchboard plug don't have the weird empty "description" space.
|Before|After|
|:---:|:---:|
|![Screenshot from 2022-10-05 11 40 43](https://user-images.githubusercontent.com/4886639/194088750-bf0c54f9-c323-4927-99e0-b67d84607ce6.png)|![Screenshot from 2022-10-05 11 39 45](https://user-images.githubusercontent.com/4886639/194088525-17df55f2-c6ac-471e-9cfb-ec05a0e268e1.png)|
> SettingsSidebarRow.vala - Fix status label showing but empty

- lib/Init.vala
Does the least to give a way for Adwaita to detect that Granite has been initialized so that it can disable styles i.e. for Epiphany
> Init: add ensure type

- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
Gtk.CssProvider.load_from_data() takes a string instead of uint8[] now.
> Fix build with newer Vala

- lib/Widgets/Settings.vala
It doesn't make sense for an int property to be owned because ints are not heap-allocated. This should fix build with latest vala.
Fixes #641
> settings: remove inappropriate ownership annotation

- lib/Init.vala
Fixes #643
Try to find a `style.css` file and if it exists, add it as an `APPLICATION` priority
> Init: load gresourced styles if present

- demo/io.elementary.granite-7.demo.desktop
meson installs as `granite-7-demo`:
```meson
executable(
'granite-7-demo',
'GraniteDemo.vala',
'Views/AccelLabelView.vala',
'Views/ApplicationView.vala',
'Views/CSSView.vala',
'Views/DateTimePickerView.vala',
'Views/DialogsView.vala',
'Views/FormView.vala',
'Views/HyperTextViewGrid.vala',
'Views/ModeButtonView.vala',
'Views/OverlayBarView.vala',
'Views/SettingsView/SettingsPage.vala',
'Views/SettingsView/SettingsView.vala',
'Views/SettingsView/SimpleSettingsPage.vala',
'Views/ToastView.vala',
'Views/UtilsView.vala',
'Views/WelcomeView.vala',
dependencies: [libgranite_dep],
install: true,
)
```
> Fix demo desktop file

- demo/GraniteDemo.vala
- demo/Views/SettingsUrisView.vala
- demo/Views/SettingsUrlsView.vala
- demo/meson.build
- lib/Constants.vala
Implements the Granite part of [Settings Urls #190](https://github.com/elementary/docs/issues/190) issue from the docs repo.
Currently covers:
- Location Services
- Online Accounts
- Network
- App Permissions
- Notifications
- Sound Input
- Custom Shortcuts
Links are showcased in a new demo app view as links:
> Settings Urls

- README.md
`granite` on Valadoc is version 6 of granite, so make sure this link points to documentations of the version 7
> README: Point to granite-7 version of valadoc

- demo/Views/UtilsView.vala
- lib/Widgets/Utils.vala
This reverts commit 9065ac67831022bb9482f9405254a18924c7332d.
Vala has reverted the API break that necessitated this change, and now we cannot build with newer Vala again.
Fixes #658
> Revert "Fix build with newer Vala (#637)"

- README.md
As we defined here:
https://github.com/elementary/granite/blob/11b720ebc92b5776a367141e93d8c303e5c8813d/demo/meson.build#L2
> README: Fix exec name of demo

- meson.build
- meson_options.txt
We don't need demo in the Flatpak Platform for example, so disabling demo when building for Flatpak should lessen its size and make build time faster a little
> Make granite-demo optional

- lib/Widgets/HeaderLabel.vala
There's some secondary text where we want to have settings links for example in https://github.com/elementary/switchboard-plug-keyboard/pull/480
> HeaderLabel: allow secondary text to use markup

- lib/Widgets/AbstractSettingsPage.vala
- lib/Widgets/AbstractSimpleSettingsPage.vala
- lib/Widgets/SettingsSidebar.vala
- meson.build
Part of fixing https://github.com/elementary/switchboard/issues/265
> Deprecate settings widgets

- demo/Views/CSSView.vala
- lib/Constants.vala
- lib/Widgets/BackButton.vala
* Replace the back button in Demo
* Deprecate the back-button style class
* Since we're providing a widget, use an image for the icon. Saves us some questionable CSS
* Allow setting the label manually in case there's some situations where we use this outside of Adw.NavigationView :shrug:
> Use Gtk.Image, deprecate style class, demo

- demo/Views/CSSView.vala
- lib/Constants.vala
- lib/Styles/Gtk/Image.scss
- lib/Styles/Gtk/Index.scss
- lib/Styles/Index-dark.scss
- lib/Styles/Index.scss
- lib/Styles/_common.scss
- lib/Styles/_label.scss
Skips accent which is handled in https://github.com/elementary/granite/pull/704
* Also add to the demo
* Add missing success constant
> Styles: add semantic colors

- demo/Views/AccelLabelView.vala
- demo/Views/ModeButtonView.vala
- lib/Styles/Gtk/Index.scss
- lib/Styles/Gtk/Popover.scss
- lib/Styles/Gtk/ShortcutsWindow.scss
Also fix keycap styles in dark mode
https://github.com/elementary/granite/assets/7277719/ec89228d-2789-4018-ac20-68dc55d81387
Doesn't include switch styles. That was just in inspector for the demo
I'm wondering if modelbutton styles should go in a separate file or not?
> Styles: add Popover and ModelButton styles

- lib/Widgets/SwitchModelButton.vala
Gtk.ModelButton is a box layout, not a bin layout. Using a box layout here means we can re-use the same border spacing from Gtk.ModelButton instead of hardcoding it
> SwitchModelButton: use box layout

- lib/Widgets/SwitchModelButton.vala
The button itself is already keyboard focusable so we don't need the switch to separately be keyboard focusable. This makes keyboard navigation faster
> SwitchModelButton: make switch not focusable

- demo/Views/CSSView.vala
- lib/Constants.vala
- lib/Styles/Gtk/Index.scss
- lib/Styles/Gtk/List.scss
* Add `BOXED_LIST` which is used in Gtk.Inspector
* Show SwitchModelButton and show/hide separators feature (this appears to be broken with io.elementary.stylesheet but works with Granite's stylesheet)
todo:
> Styles: add List styles

- lib/Widgets/Dialog.vala
> MessageDialog: Set last button as focus widget

- lib/Init.vala
- lib/Widgets/HyperTextView.vala
Fixes #717
There should be no similarities in the granite source. These are almost the copyright headers:
```
[ryo@lb760m ~/work/tmp/granite (init-doc)]$ git grepn "\/\*" | grep -v "\/\*\*"
grep: warning: stray \ before /
1:demo/GraniteDemo.vala:1:/*
2:demo/Views/AccelLabelView.vala:1:/*
3:demo/Views/ApplicationView.vala:1:/*
4:demo/Views/CSSView.vala:1:/*
5:demo/Views/DateTimePickerView.vala:1:/*
6:demo/Views/DialogsView.vala:1:/*
7:demo/Views/FormView.vala:1:/*
8:demo/Views/HyperTextViewGrid.vala:1:/*
9:demo/Views/ModeButtonView.vala:1:/*
10:demo/Views/OverlayBarView.vala:1:/*
11:demo/Views/OverlayBarView.vala:10:        /* This is necessary to workaround an issue in the stylesheet with buttons packed directly into overlays */
12:demo/Views/SettingsUrisView.vala:1:/* …
```
> Init: Make sure to use documentation comment

- lib/Widgets/Settings.vala
Review feedback for #704
I personally think this would even better for readability, but it's fine to close or modify :)
- Keep the `update_color` method just parses Variant into string representation of color
- This also makes sure that `accent_color` is only set in the `setup_accent_color` method
- Use `warning` for error message
- Set the fallback color in the catch statement instead of returning the try statement
> Init: set accent color from portal feedback

- lib/Widgets/AbstractSimpleSettingsPage.vala
`Switchboard.SimpleSettingsPage` is renamed to `Switchboard.SettingsPage` in https://github.com/elementary/switchboard/pull/283
> AbstractSimpleSettingsPage: Correct replacement class

- data/granite.metainfo.xml.in
- demo/Views/ModeButtonView.vala
- lib/Widgets/SwitchModelButton.vala
Ellipsize is not the move here for long labels. It makes it impossible to read the label. Wrap instead
> SwitchModelButton: wrap label

- lib/Widgets/Bin.vala
- lib/meson.build
We are now quite often doing an extension of widget and then setting the layout manager type to bin and doing all the other stuff with manually parenting and unparenting, so instead introduce Granite.Bin which holds only a single widget and is intended for subclassing. It's pretty much the same as [Adw.Bin](https://valadoc.org/libadwaita-1/Adw.Bin.html)
> Introduce Granite.Bin for subclassing

- lib/Widgets/SwitchModelButton.vala
Reverts elementary/granite#736
this isn’t the correct fix. Spacing should be set in CSS in granite widgets, not hardcoded
> Revert "Add space to SwitchModelButton.vala"

- lib/Widgets/Bin.vala
So that the .gir file contains the necessary annotations for other language bindings.
> Add version annotation to Granite.Bin

- data/granite.metainfo.xml.in
- demo/Views/CSSView.vala
- lib/Constants.vala
- lib/Styles/_label.scss
- meson.build
We're currently manually using pango for tnum features in a number of places: https://github.com/search?q=org%3Aelementary+tnum+language%3AVala&type=code&l=Vala
Adds `numeric` style class which has precedent in Adwaita: https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/217
Created a new `CssClass` namespace in line with: https://github.com/elementary/granite/issues/741
> Constants: add numeric css class

- README.md
Adds `gettext` to the dependency requirements. I just tried to build Granite on a fresh VM of a fresh ISO download, and meson was complaining about not being able to find msgfmt. This fixes that issue afaik.
> Add gettext to dependencies

- lib/Styles/_palette.scss
https://docs.gtk.org/gtk4/css-properties.html#non-css-colors
Also adds Latte into the mix, since it seems it never got added
> Use CSS properties defined in :root for exporting colors

- lib/Init.vala
- lib/Styles/Granite-dark.scss
- lib/Styles/Granite.scss
- lib/Styles/Gtk-dark.scss
- lib/Styles/Gtk.scss
- lib/Styles/meson.build
- lib/Styles/styles.gresource.xml
- meson.build
- meson_options.txt
- Splits Gtk and Granite stylesheets into different top level files
- Adds option to `meson_options` to enable loading the Gtk stylesheet at compile time
- I've probably unintentionally broken an API, but I don't know in what way. It seems to work fine with `granite-7-demo`
> Styles: Add compile time option for including Gtk stylesheets

- lib/Styles/Gtk/Expander.scss
- lib/Styles/Gtk/Index.scss
A small, simple, easy win (for reading Inspector in particular).
> Styles: Move expander code from stylesheet

- demo/Views/CSSView.vala
- lib/Constants.vala
- lib/Styles/Granite/_classes.scss
Turns out [everywhere we use `ROUNDED`](https://github.com/search?q=org%3Aelementary%20Granite.STYLE_CLASS_ROUNDED&type=code) is with `CARD` and the only places [we don't use rounded](https://github.com/search?q=org%3Aelementary%20Granite.STYLE_CLASS_CARD&type=code) with card are:
* in Files, Mail, and Photos because there's no easy way to crop overflow of images in GTK3, so this is not relevant and will be automatically fine in GTK4
* In AppCenter and Notifications indicator because we set a custom border radius
Basically there's no cases where we actually want square cards intentionally. So I think we can just make these round by default and deprecate the rounded class
> Styles: make cards rounded, expand demo, new constants

- lib/Widgets/Box.vala
- lib/Widgets/HeaderLabel.vala
Fixes a terminal warning. Make sure we don't add a class that has a value of ""
> Avoid adding empty style classes

- lib/Styles/Common/_animate.scss
Add missing spin keyframes to fix Gtk.Spinner animation. Can test in OverlayBar
> Styles/Animate: add spin

- lib/Styles/Common/_controls.scss
- lib/Styles/Common/_lighting.scss
- lib/Styles/Gtk/Button.scss
Since this is just the background style for controls, merge it into the controls mixin.
Headerbars are pretty much flat by default these days since everything is moving to ToolbarView and split views and the old headerbar style is out of fashion
> Styles/Controls: merge in background styles

- lib/Styles/Granite/_classes.scss
Make the borders not so harsh on cards:
> Styles/Classes: reduce card border opacity

- lib/Styles/Common/_controls.scss
- lib/Styles/Gtk/Index.scss
- lib/Styles/Gtk/Switch.scss
- lib/Styles/Index-dark.scss
Add basic switch styles. Trying something a little different where the interactive part of the control is raised and the trough is flat. The `:checked` style doesn't include accent color because I'm waiting on #704, but it is intended to use accent color eventually
> Styles: add switch

- lib/Styles/Granite/Placeholder.scss
- lib/Styles/Gtk/Entry.scss
- lib/Styles/Gtk/Index.scss
> Styles: add Entry

- .github/workflows/main.yml
- README.md
- demo/GraniteDemo.vala
- demo/Views/MapsView.vala
- demo/meson.build
- lib/Styles/Gtk/Button.scss
- lib/Styles/Index-dark.scss
- lib/Styles/Index.scss
- lib/Styles/Shumate/Index.scss
- lib/Styles/Shumate/MapMarker.scss
- lib/Styles/_osd.scss
Fixes #802 
* Does the least to provide basic styles for Shumate SimpleMap
* Add a style for button.osd
* Make sure we don't add spacing to .osd inside .linked
* Only adds a Shumate dep to the Demo. The library does not depend on Shumate
> Add basic Shumate support

- debian/control
Follows up to #704
We now require ibgtk-4-dev >= 4.12.0 due to `Gtk.CssProvider.load_from_string ()`
> control: Require libgtk-4-dev >= 4.12.0

- debian/control
Shumate was added to demo runtime deps, but we actually need to make it a build time dep
Fixes #822
> Control: move shumate to build deps

- lib/Constants.vala
These are all internal dialog construction details and shouldn't be public constants. Developers should be using the widgets not manually constructing dialogs
> Constants: deprecate dialog style classes

- demo/Views/AccelLabelView.vala
- demo/Views/ControlsView.vala
- lib/Constants.vala
Gtk.PopoverMenu has a facility for adding custom widgets, so recommend that instead of manually managing style classes for popovers.
I didn't add a constant for "model" because I think it would be better to create a Granite.ModelButton if we want to make it easier to create custom model buttons. But I left that for a future branch as well. I think we need to probably evaluate our popover menus and see what's needed, but to me that's out of scope for just deprecating these two style classes
> Constants: deprecate menu related style classes

- lib/Constants.vala
- lib/Styles/Gtk/Switch.scss
- lib/Widgets/ModeSwitch.vala
This is internal to Granite and its stylesheet. Developers shouldn't be using this style class, they should use the widget
> Constants: deprecate MODE_SWITCH

- demo/Views/CSSView.vala
- lib/Constants.vala
These constants were never used outside of Granite.
The `warmth` style was added for Nightlight, so it's only used in settings and the indicator. We should just add the styles there. I don't think they're generally useful for apps: https://github.com/search?q=org%3Aelementary+class+%28%22warmth%22%29%3B+language%3AVala&type=code
Same story with the `temperature` style. It was only used in Photos: https://github.com/search?q=org%3Aelementary+add_class+%28%22temperature%22%29+language%3AVala&type=code
> Constants: deprecate scale styles

- demo/DemoPage.vala
- demo/Views/BoxView.vala
- demo/Views/ListsView.vala
- demo/Views/MapsView.vala
- lib/Styles/Granite/Header.scss
Really thin header styles are out of fashion. We are currently carrying custom CSS for H2 headers in Icon Browser and Settings for example. So update to match those:
Add a title to demo page so we can use it in context
> Header: modernize h2 styles

- lib/Constants.vala
- lib/Widgets/AccelLabel.vala
This is an internal detail of AccelLabel. App Developers should use that, not this style class
> Constants: deprecate KEYCAP

- demo/GraniteDemo.vala
- demo/Views/VideoView.vala
- demo/meson.build
- lib/StyleManager.vala
- lib/Styles/Granite/_classes.scss
- lib/Styles/Gtk/Button.scss
- lib/Styles/Gtk/Index.scss
- lib/Styles/Gtk/Scale.scss
- lib/Styles/Gtk/Slider.scss
- lib/Styles/Gtk/Video.scss
- lib/Styles/_osd.scss
Fixes #804 
https://github.com/user-attachments/assets/0f782835-3709-4a8c-9af6-01222a96c670
* Add Gtk.Video to Demo
* Adjust provider priority. Fixes a bug where `.osd` styles were way too OP and couldn't be overridden
* Move `.circular` because this isn't just a thing that applies to buttons
Button:
* Make sure we set `color` in `button.osd` so that it doesn't inherit a non-contrasty color
* reset margins in `button.osd` instead of using expensive `:not` selector in `.osd`
* Add the same fun bounce transition we use in window controls and popovers to OSD buttons, but not when they're linked
Scale:
* add a transition for opacity to sliders
* Set rounded radius from `fill` origin, but make sure it's still square on the end
Slider:
* Don't use 50% `border-radius` in case our slider is …
> Styles: add Gtk.Video

- demo/Views/ControlsView.vala
- lib/Styles/Gtk/Index.scss
- lib/Styles/Gtk/ProgressBar.scss
Basic progressbar styles
We didn't have a vertical progress animation in the old stylesheet. I messed with it a little bit and for some reason couldn't get it to animate properly, so I wonder if that was for the same reason. Some GTK bug with calc? TBH I'm not sure we ever use vertical progressbars
> Styles/Gtk: add ProgressBar

- lib/Constants.vala
Uses of [FRAME](https://github.com/search?q=org%3Aelementary+STYLE_CLASS_FRAME+language%3AVala&type=code&l=Vala)
* with `Gtk.InfoBar` which is deprecated and needs a replacement widget anyways
* with `Gtk.ScrolledWindow` which has a property [`has_frame`](https://valadoc.org/gtk4/Gtk.ScrolledWindow.has_frame.html)
* with Gtk.ListBox which should either be `CARD` for non-scrolled boxes or on the ScrolledWindow for scrolled boxes
* When there's an ActionBar related to a ScrolledWindow/ListBox. This should probably be like a '.linked' style for ActionBar or a ToolBarview or something. There's also just `Gtk.Frame`. Lot of other possible solutions than adding a frame style to a box
> Constants: deprecate STYLE_CLASS_FRAME

- lib/Styles/Common/_controls.scss
- lib/Styles/Gtk/Button.scss
- lib/Styles/Gtk/CheckButton.scss
Fixes active/checked text-buttons not being very contrasty in dark style
> Styles/Controls: make active/checked .text-button flat

- lib/Styles/Gtk/Button.scss
- lib/Styles/Gtk/WindowControls.scss
Use non-rem units for min size to avoid blurry icons
> Styles/Gtk/Button: make all image-buttons bouncy

- demo/GraniteDemo.vala
- demo/Views/ListsView.vala
- lib/Styles/Gtk/GridView.scss
- lib/Styles/Gtk/Index.scss
> Add GridView styles

- lib/Widgets/Utils.vala
The original thought process behind using "⌘" was that:
1. No keyboards have the word "Super"
2. We can't use the Windows logo because of trademark
3. Some keyboards have the "⌘" symbol
But now, we have hardware partners like StarLabs which do print keyboards with the word "Super" on the super key. Plus the screen reader announces "⌘" as "Mac command key" instead of "Super". So it would probably be better at this point to switch to the word "Super"
> accel_to_string: ⌘ → Super

- lib/Styles/_exported.scss
Added back the variables that dock expects to be exported as gtk variables because I got tired of looking at an invisible dock
> Export variables expected by dock

- lib/StyleManager.vala
This is for instance the case for the portal application.
> StyleManager: Allow the GLib.Application to be null

- demo/Views/WelcomeView.vala
- demo/data/demo.gresource.xml
- demo/data/git.svg
- demo/data/meson.build
- demo/data/valadoc.svg
- demo/meson.build
Towards #874 
Gresource welcome icons instead of relying on non-fd.o file type icons.
> Demo: gresource welcome icons

- data/granite.metainfo.xml.in
- demo/Views/BoxView.vala
Fixes #874 
Replace non-fd.o icon with `package-x-generic`, arguably more "boxy" anyways :)
> Demo: application-default-icon → package-x-generic

- lib/Widgets/Utils.vala
Fix [the documentation on Valadoc](https://valadoc.org/granite-7/Granite.markup_accel_tooltip.html) is not shown as expected:
- `Returns` says that the returned value has two lines but `Example:` is not because we're missing the `<<BR>>` markup
- The description of `accels` is grayed out because we're missing the name of the parameter
> Utils: markup_accel_tooltip: Correctly markup documentation

- lib/StyleManager.vala
Fixed the following errors by valadoc when you build Granite with `-Ddocumentation=true`
```
StyleManager.vala:47.131-47.132: error: expected }: <space>
* Uses value from {@link Granite.Settings.prefers_color_scheme} when set to {@link Granite.Settings.ColorScheme.NO_PREFERENCE }.
^   
StyleManager.vala:24.51-24.52: error: expected }: <space>
* as gotten by {@link Gdk.Display.get_default ()}.
^     
Failed: 2 error(s), 10 warning(s)
```
> StyleManager: Fix build error with valadoc

- .github/workflows/main.yml
- README.md
Running `meson build` shows the following warning:
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
Also I think this could lead newcomers misunderstand that `build` is an subcommand of meson, not a build directory.
> meson: Explicit setup

- demo/Views/HyperTextViewGrid.vala
- demo/Views/WelcomeView.vala
As raised in https://github.com/elementary/granite/pull/892#issuecomment-3336093976
> demo: Replace deprecated Granite.STYLE_CLASS_FRAME
