elementary/granite

demo/CMakeLists.txt
demo/GraniteDemo.vala
demo/Views/AlertViewView.vala
demo/Views/DateTimePickerView.vala
demo/Views/DynamicNotebookView.vala
demo/Views/ModeButtonView.vala
demo/Views/SourceListView.vala
demo/Views/StorageView.vala
demo/Views/ToastView.vala

This moves all of the views in the demo to their own files. It makes it much easier to find the "code samples"
Each view should be its own commit (with the exception of toasts which snuck in with modebutton, sorry) for easier reviewing

Demo views

---

demo/CMakeLists.txt
demo/GraniteDemo.vala
demo/Views/AvatarView.vala

This adds a view where you can see the avatar widget at standard icon sizes

Demo: Add an avatar view

---

demo/Views/SourceListView.vala

SourceList Demo: Better represent what SourceList looks like in practice

---

lib/Widgets/ModeButton.vala

Make ModeButton use toggled instead of button_press_event

---

demo/CMakeLists.txt
demo/GraniteDemo.vala
demo/Views/CSSView.vala

Adds a view showing off our rad CSS classes

Demo: Add CSSView

---

lib/GtkPatch/AboutDialog.vala

* Remove `using Gtk` and namespace Gtk explicitly
* Remove `using Gdk` and namespace Gdk explicitly
* One true brace style
* Space before parentheses

GtkPatch.AboutDialog.vala Remove using libs

---

demo/Views/OverlayBarView.vala
lib/Widgets/OverlayBar.vala

Now with 100% less witchcraft!
* GObject-style construction
* Update the Demo to use label property
* No nasty Cairo code
* Updated fallback styles

OverlayBar.vala: Remove cairo drawing

---

lib/Application.vala

Since AppMenu itself is now also deprecated

Application.vala: deprecate create_appmenu

---

lib/Widgets/AboutDialog.vala

Since we're all GitHub now, don't try to launch apport

Don't try to launch apport

---

lib/GtkPatch/AboutDialog.vala
lib/Widgets/AlertView.vala
lib/Widgets/Avatar.vala
lib/Widgets/StorageBar.vala
lib/Widgets/Welcome.vala
lib/Widgets/WelcomeButton.vala
lib/style-classes.vala

This ensures we get deprecation warnings if these style classes were ever to change and gives stylesheet authors stable class names to target

Replace undocumented style classes with public constants

---

lib/Widgets/Toast.vala

Fixes #71 
Duration is currently private in this branch. I guess if we're deciding that we don't want everlasting toasts we might want to consider if duration should even be public at all

Toast.vala: Add timeouts

---

demo/CMakeLists.txt
demo/GraniteDemo.vala
demo/Views/SettingsView.vala
lib/CMakeLists.txt
lib/Widgets/DynamicNotebook.vala
lib/Widgets/SettingsPage/AbstractSettingsPage.vala
lib/Widgets/SettingsPage/AbstractSimpleSettingsPage.vala

This is a smaller PR as a step towards #70. The SimpleSettingsPage itself is still valuable independent of SettingsSidebar in the Bluetooth plug for example.
SettingsPage is pretty useless in this PR, but I decided to include it to avoid changing API between this merge and a merge including SettingsSidebar

Add SettingsPage and SimpleSettingsPage

---

lib/Widgets/CompositedWindow.vala

Describe the `CompositedWindow` a little bit more and add examples how to use it.

Describe the CompositedWindow more precisely

---

lib/Widgets/SourceList.vala

SourceList: Remove deprecated sort direction

---

lib/Widgets/AppMenu.vala

remove appmenu.with_urls

---

lib/StyleClass.vala
lib/Widgets/MessageDialog.vala

make sure we're using style constants for our styles

Add primary style class

---

demo/GraniteDemo.vala
demo/Views/DateTimePickerView.vala
lib/DateTime.vala

Fixes #91 
Adds the relative date time functions from Mail
For some reason relative date time doesn't seem to work properly until you change the date once. weird.

add relative date time utils

---

lib/Widgets/DynamicNotebook.vala

Fixes #109 
Reopens #82 
Not exactly ideal, but it fixes the regression and 109 is a worse problem than 82

DynamicNotebook: Fix regression with tab duplication on close

---

lib/Widgets/MessageDialog.vala
lib/Widgets/OverlayBar.vala

while we're here, we need to set start margins on action area because of RTL

Replace deprecated margin_left and margin_right

---

demo/GraniteDemo.vala
demo/Views/AlertViewView.vala
demo/Views/AsyncImageView.vala
demo/Views/AvatarView.vala
demo/Views/CSSView.vala
demo/Views/DateTimePickerView.vala
demo/Views/DynamicNotebookView.vala
demo/Views/MessageDialogView.vala
demo/Views/ModeButtonView.vala
demo/Views/OverlayBarView.vala
demo/Views/SeekBarView.vala
demo/Views/SettingsView/SettingsPage.vala
demo/Views/SettingsView/SettingsView.vala
demo/Views/SettingsView/SimpleSettingsPage.vala
demo/Views/SourceListView.vala
demo/Views/StorageView.vala
demo/Views/ToastView.vala
demo/Views/WelcomeView.vala
lib/Widgets/widgets-utils.c

Updates FSF address in license headers

Update FSF address

---

demo/Views/CSSView.vala
lib/StyleClass.vala

This was introduced in https://github.com/elementary/stylesheet/commit/383aa236c22e8d9ae8dc87ab8983be9f3019a283

StyleClass.vala: Add and document .terminal

---

lib/StyleClass.vala

Adds documentation for many style class constants

 StyleClass.vala: much better documentation

---

lib/Widgets/Welcome.vala

* No `using`
* Gtk.Grid instead of Gtk.Box
* Document style class
* Add a code sample
* Document string casing
* Use links with other widgets

Widgets.Welcome improvements

---

demo/GraniteDemo.vala

Added theme toggle button

---

README.md

added basic projedt description into readme.  addressing #154

---

lib/Widgets/OverlayBar.vala

Queue a recompute of the positioning of the overlaybar on hover

---

demo/Views/CSSView.vala
lib/StyleClass.vala

Create and document a style class constant for giving text and icons the app accent color

StyleClass: accent constant

---

lib/Widgets/AbstractSimpleSettingsPage.vala

TIL we don't already do this. Oops

SimpleSettingsPage: Ellipsize long page titles

---

lib/Widgets/AbstractSimpleSettingsPage.vala

SimpleSettingsPage: Hide action area if empty

---

demo/Views/CSSView.vala
lib/StyleClass.vala

Goes with https://github.com/elementary/stylesheet/pull/341

Style class mode switch

---

lib/Widgets/AlertView.vala

Fixes #166 
Also get rid of a random eventbox

AlertView: Hide icon if no icon name

---

demo/GraniteDemo.vala

Because Granite.App is no longer necessary

GraniteDemo: Use Gtk.Application

---

demo/Views/CSSView.vala
lib/StyleClass.vala

StyleClass: add checkerboard

---

demo/GraniteDemo.vala
demo/Views/CSSView.vala
demo/Views/ModeButtonView.vala

Since it's a proper widget now and not just a style class

Demo: Move ModeSwitch to ModeButton page

---

lib/Widgets/Utils.vala

Don't add duplicate accels

---

demo/Views/UtilsView.vala
lib/Widgets/Utils.vala

Contrasting foreground color

---

lib/Widgets/AbstractSimpleSettingsPage.vala

Also bump copyright and fix whitespace while we're here

AbstractSimpleSettingsPage: Use Granite style constant

---

lib/Widgets/AbstractSimpleSettingsPage.vala

title and desc selectable for SimpleSettingsPage

---

lib/Widgets/DynamicNotebook.vala
meson.build

Fixes: #18 
As I am relatively new to vala/gtk I could use some feedback:
Is there a better way than 
https://github.com/andreasfelix/granite/blob/2d9637c2e798594aa231b5fe3b726146d5dc67f2/lib/Widgets/DynamicNotebook.vala#L320-L322
to get the positon of a tab?
Is 
https://github.com/andreasfelix/granite/blob/2d9637c2e798594aa231b5fe3b726146d5dc67f2/lib/Widgets/DynamicNotebook.vala#L1205-L1214
an appropiate way to close all tabs to the right?

Close Tabs to the Right

---

lib/Widgets/Utils.vala

Utils: Add equal keys to accel_to_string

---

demo/GraniteDemo.vala
demo/Views/AlertViewView.vala
demo/Views/AsyncImageView.vala
demo/Views/CSSView.vala
demo/Views/DynamicNotebookView.vala
demo/Views/MessageDialogView.vala
demo/Views/ModeButtonView.vala
demo/Views/OverlayBarView.vala
demo/Views/SeekBarView.vala
demo/Views/SettingsView/SettingsPage.vala
demo/Views/UtilsView.vala

I just ran the latest vala-lint commands on the demo directory and fixed any errors/warnings that came up. For local testing you can test it out as well via running vala-lint directly (or via a docker image).
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d demo
```
Assiming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint -d demo
```

:shirt: Use vala-lint to lint demo directory.

---

demo/Views/MessageDialogView.vala

MessageDialogView: Sentence-case primary label

---

demo/Views/DynamicNotebookView.vala
demo/Views/StorageView.vala

Updated copyright while we're here.

Demo Views: Lint

---

lib/Widgets/SourceList.vala

Just a bunch of wrapping/whitespace fixes.

SourceList: Lint

---

lib/Services/Paths.vala

Lots of end-of-line whitespace changes, so view with whitespace changes off :)

Paths: Lint

---

lib/Services/Settings.vala

Lots of end-of-line whitespace

Settings: Lint

---

lib/Widgets/CellRendererBadge.vala
lib/Widgets/CellRendererExpander.vala

Two in one since they were both tiny and related

CellRenderers: Lint

---

lib/Widgets/MessageDialog.vala

Lots of whitespace and a couple of line-length warnings

MessageDialog: Lint

---

lib/Widgets/AsyncImage.vala

AsyncImage: Lint

---

lib/Widgets/AppMenu.vala

AppMenu: Lint

---

lib/Services/IconFactory.vala

IconFactory: Lint

---

lib/Drawing/Color.vala

Mostly whitespace plus an internal variable naming style. Public vars are given a lint exception comment since they're API.

Drawing Color: Lint

---

lib/Drawing/Utilities.vala

Whitespace, line-length, and variable names

Drawing Utilities: Lint

---

lib/GtkPatch/AboutDialog.vala
lib/Widgets/AboutDialog.vala

This one has kind of a ton of code style fixes, but it's all wrapping and whitespace related.

AboutDialog: Lint

---

lib/Application.vala

~Since this is protected and just used below, is it fine to change to lowercase? https://github.com/elementary/granite/blob/389005fd0329f9bb4d600e90a78fd5aa67f1023a/lib/Application.vala#L195~

Application: Lint

---

lib/Widgets/DynamicNotebook.vala

Changes:
- code wrapping style
- remove double spaces
- space before parens
- nest long lines
- replace tabs with spaces
- rewrite 120+-line "shorthand" if/elses into nested if/elses

DynamicNotebook: Lint

---

.github/workflows/lint.yml
.github/workflows/main.yml

Add Lint to CI

---

lib/Widgets/AccelLabel.vala
lib/Widgets/Utils.vala

AccelLabel and Utils: Add null checks

---

data/granite.appdata.xml.in
lib/Widgets/SettingsSidebarRow.vala

SettingsSidebarRow: center align with no subtitle

---

data/granite.appdata.xml.in
meson.build

Lots of translations and a couple of nice improvements

Release 5.3.1

---

lib/Services/Settings.vala

Settings: Deprecate and suggest GLib.Settings

---

meson.build

Should allow daily builds for dark mode stuff

5.4.0 version bump

---

data/granite.appdata.xml.in
demo/Views/CSSView.vala
lib/StyleClass.vala
meson.build

Fixes #263. Usage in the demo is only supported in greenfield stylesheet.

StyleClass: Add .rounded style constant

---

data/granite.appdata.xml.in
lib/StyleClass.vala

Since we support this in Greenfield

StyleClass: Add color-button

---

lib/Widgets/SourceList.vala

* Add `sidebar` style class
* Apply styles without deprecated utils

SourceList: Rewrite default style

---

data/granite.appdata.xml.in
demo/Views/CSSView.vala
lib/StyleClass.vala

Relates to #306 ~(or not; I don't know what the "temperature" class referred there is)~.
Here's what the demo looks like:

Add "warmth" style const with demo

---

demo/Views/CSSView.vala

Fixes some alignment issues and modernizes the codestyle. While we're here, bump copyright.

CSSView: Codestyle and alignment

---

lib/Widgets/Toast.vala

Reset toast visibility timeout on Toast.send_notification ()

---

data/granite.appdata.xml.in
lib/Constants.vala

Closes https://github.com/elementary/granite/issues/395

Add `default-decoration` style class constant

---

lib/Constants.vala

Constants: Add SMALL_LABEL

---

meson.build

So that apps in daily can bump their minimum expected version for new API
This is not a release commit

Bump version to 6

---

demo/Views/FormView.vala
lib/Widgets/ValidatedEntry.vala

And also `.for_purpose (InputPurpose)` constructor with associated enum

From regex constructor

---

lib/Drawing/Utilities.vala

View with hide whitespace changes
Only two little inline namespace things

Granite.Drawing.Utilities: minor codestyle cleanup

---

lib/Widgets/SettingsSidebar.vala

SettingsSidebar: Sync visible_child_name with stack.visible_child_name

---

lib/Widgets/AbstractSettingsPage.vala

AbstractSettingsPage: Fix 'status' is set-only

---

lib/Widgets/SwitchModelButton.vala

Bind active property bidirectionally

---

lib/Config.vala.in
lib/DateTime.vala
lib/Widgets/DynamicNotebook.vala
lib/meson.build

ngettext is using the domain from `textdomain()` which is specified by the applications and
thus never returns the right domain when used in an application.

Use dngettext instead of ngettext

---

.github/workflows/release.yml
data/granite.appdata.xml.in

So we can get this going in the Sdk etc without just pulling master

Release 6.0.0

---

lib/Application.vala
lib/Services/System.vala
meson.build

Add support for windows.
Working on mingw to run Akira:
https://github.com/msys2/MINGW-packages/pull/8505/files#diff-18b1226b74e8b4adf04b5e3401ac6886ead2da9a1dc26b6c61be29141ca0f641R23

Build on windows

---

meson.build

Increased required vala compiler version

---

data/granite.appdata.xml.in
lib/Constants.vala

To be used in places like https://github.com/elementary/applications-menu/pull/453 and the Notebook close button fade in/out.

Add TRANSITION_DURATION_IN_PLACE

---

lib/Init.vala
lib/Widgets/AccelLabel.vala
lib/Widgets/DynamicNotebook.vala
lib/Widgets/MessageDialog.vala
lib/Widgets/StorageBar.vala
lib/Widgets/TimePicker.vala
lib/Widgets/Utils.vala
lib/meson.build

Provides the directory where the locales are actually installed.
Localization is only setup on-demand.
Supersedes #518

l10n: Correctly setup the locales

---

data/granite.appdata.xml.in
meson.build

Release 6.2.0

---

lib/Widgets/DynamicNotebook.vala

DynamicNotebook: Do not use deprecated child property

---

lib/Constants.vala

Constants: Add destructive-action

---

lib/Constants.vala

Used in https://github.com/elementary/initial-setup/pull/134

Constants: add view and warning classes

---

lib/Constants.vala
lib/Widgets/MessageDialog.vala

Makes us more compatible with Adwaita at no real cost

Constants: use header class names from Adw

---

lib/Widgets/Utils.vala

Utils: fix set_color_primary

---

lib/Constants.vala

This is my only blocker for https://github.com/elementary/shortcut-overlay/pull/112 so wanted to split it out from the Dialogs branch

Constants: add "title"

---

lib/Widgets/SwitchModelButton.vala

SwitchModelButton: ellipsize label at 25ch

---

lib/Widgets/SettingsSidebar.vala

* Make this a widget subclass instead of Box to avoid unintended API
* Remove hardcoded min width. This should be in CSS if it's necessary

SettingsSidebar: subclass Gtk.Widget

---

lib/Widgets/SettingsSidebarRow.vala

Use CSS for styles instead of hardcoding values
Depends:

SettingsSidebarRow: remove hardcoded styles

---

lib/Widgets/AbstractSimpleSettingsPage.vala

* Use CSS for styles instead of hardcoding
* Code style
Depends on:

AbstractSimpleSettingsPage: remove hardcoded styles

---

demo/Views/SettingsView/SimpleSettingsPage.vala
lib/Widgets/AbstractSimpleSettingsPage.vala

SimpleSettingsPage: Allow markup in description

---

README.md

README: Update required GTK version

---

debian/control

Recommend settings daemon for methods that use portals?

Control: Add settings-daemon to recommends

---

data/granite.appdata.xml.in
lib/Widgets/MessageDialog.vala

Fix code style while we're here

MessageDialog: Fix large height bug

---

lib/Init.vala

This only became public in 7.2.0

Add since annotation to new public init method

---

.github/workflows/main.yml
lib/Constants.vala
meson.build

Tidies up the indentation while we're here

Constants: Add since versions to new URI values

---

lib/Widgets/HeaderLabel.vala
meson.build

HeaderLabel: Add mnemonic_widget property

---

demo/Views/CSSView.vala

h* style classes are renamed to title-* in 15bd5ebf87177d5aa79687fef4eed42c9c679c3f

CSSView: Update title class name label

---

demo/Views/WelcomeView.vala
lib/Styles/Granite/Placeholder.scss

Placeholder: resize based on parent

---

lib/Styles/meson.build
lib/Styles/styles.gresource.xml

Allows the internal Granite styles to be used as a system theme

Styles: install theme to host

---

lib/Init.vala
lib/Styles/Index-dark.scss
lib/Styles/Index.scss
lib/Styles/_common.scss
lib/Styles/meson.build
lib/Styles/styles.gresource.xml

Generates and loads a dark variant of styles

Styles: add dark variant

---

lib/Styles/Gtk/WindowControls.scss
lib/Styles/Index-dark.scss
lib/Styles/Index.scss
lib/Styles/_animate.scss

Basic styles for window controls with a lightly animated pressed state
[Peek 2024-02-23 12-08.webm](https://github.com/elementary/granite/assets/7277719/0022cc11-e820-47fc-a1f3-37d19a9fc36e)

Styles: add WindowControls

---

lib/Styles/Granite/Index.scss
lib/Styles/Gtk/Index.scss
lib/Styles/Index-dark.scss
lib/Styles/Index.scss

Makes this a bit more maintainable

Styles: add Index files in widget subfolders

---

lib/Styles/Granite/Dialog.scss
lib/Styles/Gtk/Window.scss

and smaller shadow for dialogs

Styles: add highlight to windows

---

lib/Styles/Granite/OverlayBar.scss
lib/Styles/Gtk/Index.scss
lib/Styles/Gtk/Tooltip.scss

And fix overlaybar shadows while here

Styles: add Tooltip style

---

lib/Styles/Gtk/Index.scss
lib/Styles/Gtk/Scrollbar.scss

Fixes https://github.com/elementary/stylesheet/issues/1180

Styles: add scrollbar

---

demo/GraniteDemo.vala

Demo: use paned design

---

lib/Widgets/AbstractSettingsPage.vala
lib/Widgets/AbstractSimpleSettingsPage.vala
lib/Widgets/DynamicNotebook.vala
lib/Widgets/SettingsSidebar.vala
lib/Widgets/SourceList.vala
lib/Widgets/StorageBar.vala
meson.build

Deprecate widgets removed in Granite 7

---

lib/Widgets/MessageDialog.vala

Same as https://github.com/elementary/granite/pull/734, just applied to the right branch (`main`).

Fix dead link (#734)

---

lib/Widgets/SwitchModelButton.vala

Add space to SwitchModelButton.vala

---

lib/Icons/icons.gresource.xml

Icons: add alias for adw-entry-apply-symbolic

---

lib/Icons/icons.gresource.xml
lib/Icons/scalable/eye-not-looking-symbolic.svg
lib/Icons/scalable/eye-open-negative-filled-symbolic.svg

non-fdo interface icons required by Gtk.PasswordEntry

Icons: add eye icons required by Gtk.PasswordEntry

---

demo/Views/CSSView.vala
demo/Views/WelcomeView.vala
lib/Constants.vala

Constants/CssClass: add colors and deprecate old ones

---

demo/Views/BoxView.vala
lib/Widgets/HeaderLabel.vala

And fix a deprecation warning in Demo while we're here

HeaderLabel: add default for to_string

---

demo/DemoPage.vala
demo/GraniteDemo.vala
demo/Views/AccelLabelView.vala
demo/Views/ApplicationView.vala
demo/Views/BoxView.vala
demo/Views/CSSView.vala
demo/Views/DateTimePickerView.vala
demo/Views/DialogsView.vala
demo/Views/FormView.vala
demo/Views/HyperTextViewGrid.vala
demo/Views/ModeButtonView.vala
demo/Views/OverlayBarView.vala
demo/Views/SettingsUrisView.vala
demo/Views/StyleManagerView.vala
demo/Views/ToastView.vala
demo/Views/UtilsView.vala
demo/Views/WelcomeView.vala
demo/meson.build

Sets things up for a future where each page might have its own title like Switchboard pages and/or be a ToolbarView subclass. Views no longer add their own scrolledwindow

Demo: create DemoPage

---

lib/Styles/Gtk/Popover.scss

Add basic `.emoji-picker` styles

Styles/Popover: add emoji-picker

---

demo/Views/ControlsView.vala
lib/Styles/Granite/Box.scss
lib/Widgets/Box.vala

And add some documentation to size enum

Box: add half spacing

---

lib/Styles/Gtk/Popover.scss

Adds styles for Gtk.PopoverMenu:

Styles/Popovers: add styles for Gtk.PopoverMenu

---

debian/control

control: Add libshumate-dev as dependency of demo

---

demo/Views/ControlsView.vala
lib/Styles/Common/_controls.scss
lib/Styles/Gtk/Index.scss
lib/Styles/Gtk/Scale.scss
lib/Styles/Gtk/Slider.scss
lib/Styles/Gtk/Switch.scss

Fixes #808 
* Add basic scale styles
* Make slider its own file to share styles
* Make trough styles a mixin to share
Let me know if anything needs more comprehensive comments!

Styles: add Scale

---

lib/Constants.vala

We do already support this for buttons

Constants: add CssClass.CIRCULAR

---

demo/Views/CSSView.vala
lib/Constants.vala

We still use this all over the place outside of HeaderLabels

Constants: add CssClass.SMALL

---

lib/Styles/Gtk/Button.scss

Styles: Add padding and minimum sizes for buttons

---

lib/Styles/Gtk/Index.scss
lib/Styles/Gtk/Selection.scss
lib/Styles/_exported.scss

Add selection style. Gotta use GTK variables since we use accent color

Styles/GTK: add selection

---

lib/Styles/Gtk/Index.scss
lib/Styles/Gtk/_classes.scss

I don't think this is used anywhere else but :shrug:

Styles/Gtk: add .toolbar

---

lib/Styles/Gtk/Button.scss

Makes it a lot easier to see the state of these buttons in Inspector :p

Styles/Gtk/Button: checked extends selection

---

lib/Icons/icons.gresource.xml
lib/Icons/scalable/view-sidebar-end-symbolic.svg
lib/Icons/scalable/view-sidebar-start-symbolic.svg

Icons used for hiding/showing sidebars such as in Documents and Web:

Icons: add sidebar icons

---

lib/Styles/Index-dark.scss

And use new color constants while we're here
##AFTER

Styles: make dark theme darker

---

demo/Views/ControlsView.vala

Just makes it easier to see styles at a glance if we check the toggle buttons by default

Demo: check toggles by default

---

.github/workflows/lint.yml
.github/workflows/release.yml

The branch still exists but seems to be behind from the main

Actions: Use main branch
